---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: python
os: linux
git:
  depth: 1
dist: bionic
cache:
  directories:
    - /home/travis/.vagrant.d/boxes
    - /home/travis/.cache/molecule
jobs:
  include:
    - name: Pod Definition File validation
      language: shell
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
      script:
        - cp config/samples/pdf.yml.aio config/pdf.yml
        - sudo vagrant up
    - name: Lint validation
      install:
        - pip install tox
      script:
        - tox -e lint
        - bash -c 'shopt -s globstar; shellcheck -x **/*.sh'
    - name: Documents validation
      install:
        - pip install tox
      script:
        - tox -e docs
    - name: All-in-One Ubuntu 16.04 LTS validation
      language: shell
      dist: xenial
      script:
        - KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
    - name: All-in-One Ubuntu 18.04 LTS validation
      language: shell
      script:
        - KRD_FOLDER=$(git rev-parse --show-toplevel) ./aio.sh
    - name: NFD role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e nfd
    - name: PMEM role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e pmem
    - name: QAT driver installation role validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e qat_driver
    - name: SR-IOV roles validation
      install:
        - sudo apt update; sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
        - pip install tox
      script:
        - sudo $(command -v tox) -e sriov_cni,sriov_plugin
