---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  set -e
  PATH=${PATH}
  yamllint -c ../../../.yamllint .
platforms:
  - name: centos7
    box: generic/centos7
    memory: 3072
    cpus: 1
  - name: bionic
    box: generic/ubuntu1804
    memory: 3072
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
