---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: boostrap servers
  hosts: all
  vars:
    kind_dest: /usr/local/bin
  roles:
    - role: andrewrothstein.kind
      kind_install_dir: '{{ kind_dest }}'
    - andrewrothstein.kubectl
    - role: geerlingguy.docker
      docker_install_compose: false
      become: true
  tasks:
    - name: add existing user ansible's user to docker's group
      become: true
      user:
        name: '{{ ansible_ssh_user }}'
        groups: docker
        append: true
    - name: get k8s clusters
      command: '{{ kind_dest }}/kind get clusters --quiet'
      register: kind_cluster
      failed_when: ( kind_cluster.rc not in [ 0, 1 ] )
    - name: print kind_cluster value
      debug:
        var: kind_cluster
    - name: create k8s cluster
      become: true
      command: '{{ kind_dest }}/kind create cluster --name molecule --wait=300s'
      when: not 'molecule' in kind_cluster.stdout
    - name: create kubeconfig folder
      file:
        mode: '0755'
        path: '{{ ansible_env.HOME }}/.kube/'
        state: directory
    - name: copy kubeconfig root file
      become: true
      copy:
        mode: preserve
        src: /root/.kube/config
        dest: '{{ ansible_env.HOME }}/.kube/config'
        remote_src: true
        owner: '{{ ansible_ssh_user }}'
        group: '{{ ansible_ssh_user }}'
    - name: download pip installer
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
        mode: 0440
    - name: install pip
      become: true
      command: /usr/bin/python /tmp/get-pip.py
    - name: install python dependencies
      become: true
      pip:
        name: "{{ item.name | default(item) }}"
        version: "{{ item.version | default(omit) }}"
      with_items:
        - name: kubernetes
          version: 11.0.0
        - openshift
