---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2022
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
name: Documentation and diagram generation
# yamllint disable-line rule:truthy
on:
  push:
    paths-ignore:
      - codebase-structure.svg
      - .github/
  workflow_dispatch:
jobs:
  check-diagram:
    name: Update the codebase structure diagram
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github"
          output_file: codebase-structure.svg
          should_push: false
      - uses: technote-space/create-pr-action@v2.1.4
        with:
          COMMIT_MESSAGE: 'Upgrade documentation diagram'
          COMMIT_NAME: 'electrocucaracha bot'
          PR_BRANCH_NAME: "versions-update-${PR_ID}"
          PR_TITLE: 'chore: update diagram'
